# src/main/resources/application.yml
spring:
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3307/coupon_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: coupon_user
    password: coupon_pw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:coupon_schema.sql
  #    init:
  #      mode: embedded  #always | never | embedded

server:
  port: 8081

circuit-test:
  coupon:
    delay-prefix: CPN-INT-CIRCUIT-ON
    delay-ms: 8000

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://mysql.msa.svc.cluster.local:3306/coupon_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: coupon_user
    password: ${COUPON_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:coupon_schema.sql
  #    init:
  #      mode: embedded  #always | never | embedded

server:
  port: 8081

circuit-test:
  coupon:
    delay-prefix: CPN-INT-CIRCUIT-ON
    delay-ms: 8000
