# src/main/resources/application.yml
spring:
  profiles:
    active: h2  # file | h2

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:orderorchestrator;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    #url: "jdbc:h2:file:${user.home}/test/account-db;MODE=LEGACY"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    hibernate:
      ddl-auto: update
    show-sql: true
#    init:
#      mode: embedded  #always | never | embedded
  h2:
    console:
      enabled: true  # http://localhost:8080/h2-console
      path: /h2-console

server:
  port: 8080

persistence:
  type: h2
#mybatis:
#  mapper-locations: classpath*:mappers/**/*.xml     # ★ XML 위치
#  type-aliases-package: com.example.account.domain.model
#  configuration:
#    map-underscore-to-camel-case: true