### 주문 생성 요청 (Happy Path 예시)
POST http://localhost:8080/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "couponNumber": "CPN-20250101-0001",
  "paymentNumber": "PAY-20250101-0001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# (선택) 서버 헬스 체크
GET http://localhost:8080/actuator/health
Accept: application/json

###

# H2 콘솔 호출 (HTML 응답, 브라우저에서 여는 게 확인하기 편함)
GET http://localhost:8080/h2-console


# H2 DB 데이터 확인
SELECT * FROM ORDER_ITEM ;
SELECT * FROM ORDER_SAGA ;
SELECT * FROM OUTBOX_MESSAGE ;