### 주문 생성 요청 (K8s Happy Path 예시)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "couponNumber": "CPN-BOTH-001",
  "pointNumber": "PNT-BOTH-001",
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# 주문 생성 요청 (쿠폰 예약 불가 + 포인트 예약 가능)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "couponNumber": "CPN-BOTH-RESERVED-001",
  "pointNumber": "PNT-BOTH-AVAILABLE-001",
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# 주문 생성 요청 (쿠폰만)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "couponNumber": "CPN-ONLY-001",
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# 주문 생성 요청 (포인트만)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "pointNumber": "PNT-ONLY-001",
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# 주문 생성 요청 (쿠폰/포인트 없음)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# (선택) 서버 헬스 체크
GET http://localhost:8099/actuator/health
Accept: application/json
