### 로컬 쿠버네티스에서 MSA 서비스 실행 ###
# bin_k8s/03_deploy_all.sh
## 이미 실행중인데 재기동 (테스트 데이터 초기화)
# bin_k8s/05_restart_msa.sh
#
# 프로세스 종료는
# bin_k8s/


### 주문 생성 요청 (K8s Happy Path 예시)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "couponNumber": "CPN-INT-BOTH-001",
  "pointNumber": "PNT-INT-BOTH-001",
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# 주문 생성 요청 (쿠폰 예약 불가 + 포인트 예약 가능)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "couponNumber": "CPN-INT-BOTH-RESERVED-001",
  "pointNumber": "PNT-INT-BOTH-AVAILABLE-001",
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# 주문 생성 요청 (쿠폰만)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "couponNumber": "CPN-INT-ONLY-001",
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# 주문 생성 요청 (포인트만)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "pointNumber": "PNT-INT-ONLY-001",
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# 주문 생성 요청 (쿠폰/포인트 없음)
POST http://localhost:8099/api/v1/orders
Content-Type: application/json
Accept: application/json

{
  "paymentNumber": "PAY-001",
  "paymentAmount": 35000,
  "orderItems": [
    {
      "itemNumber": "ITEM-001",
      "quantity": 2
    },
    {
      "itemNumber": "ITEM-002",
      "quantity": 1
    }
  ]
}

###

# (선택) 서버 헬스 체크
GET http://localhost:8099/actuator/health
Accept: application/json
